# Generated by Django 5.1.1 on 2024-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('alias', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=300, null=True)),
                ('small_head_img_url', models.CharField(blank=True, max_length=300, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('label_name', models.CharField(blank=True, max_length=300, null=True)),
                ('is_valid', models.BooleanField(blank=True, default=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneData',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('phone_name', models.CharField(blank=True, max_length=300, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(blank=True, max_length=300, null=True)),
                ('talker_id', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('subtype', models.IntegerField(blank=True, null=True)),
                ('is_sender', models.BooleanField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=300, null=True)),
                ('str_content', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('str_time', models.CharField(blank=True, max_length=300, null=True)),
                ('msg_svr_id', models.CharField(blank=True, max_length=300, null=True)),
                ('bytes_extra', models.TextField(blank=True, max_length=16383, null=True)),
                ('compress_content', models.CharField(blank=True, max_length=300, null=True)),
                ('display_content', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
