# Generated by Django 5.1.1 on 2024-10-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0003_contact_phone_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatmessage',
            name='Contact_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WachatMsgServer.contact'),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
