# Generated by Django 5.1.1 on 2024-10-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0004_wechatmessage_contact_data_alter_wechatmessage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedata',
            name='is_valid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
