# Generated by Django 5.1.1 on 2024-10-09 13:38

import WachatMsgServer.models
import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0005_phonedata_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatmessage',
            name='my_json_field',
            field=models.JSONField(default=dict, encoder=json.encoder.JSONEncoder),
        ),
    ]
