# Generated by Django 5.1.1 on 2024-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0006_wechatmessage_my_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmessage',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
