# Generated by Django 5.1.1 on 2024-10-10 12:03

import WachatMsgServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0007_alter_wechatmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmessage',
            name='bytes_extra',
            field=models.BinaryField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='my_json_field',
            field=models.JSONField(default=dict),
        ),
    ]
