# Generated by Django 5.1.1 on 2024-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0008_alter_wechatmessage_bytes_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatmessage',
            name='my_json_field',
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='alias',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='avatar_path',
            field=models.CharField(default=':/icons/icons/default_avatar.svg', max_length=255),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='is_chatroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='nickName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='smallHeadImgBLOG',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='smallHeadImgUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='wxid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
