# Generated by Django 5.1.1 on 2024-10-10 12:30

import WachatMsgServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0009_remove_wechatmessage_my_json_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatmessage',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='avatar_path',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='is_chatroom',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='nickName',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='smallHeadImgBLOG',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='smallHeadImgUrl',
        ),
        migrations.RemoveField(
            model_name='wechatmessage',
            name='wxid',
        ),
        migrations.AddField(
            model_name='wechatmessage',
            name='my_json_field',
            field=models.JSONField(default=dict),
        ),
    ]
