# Generated by Django 5.1.1 on 2024-10-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0010_remove_wechatmessage_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmessage',
            name='compress_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wechatmessage',
            name='display_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
