# Generated by Django 5.1.1 on 2024-10-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0012_chartdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_sender',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_types',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_weekday',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
