# Generated by Django 5.1.1 on 2024-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0013_alter_chartdata_chart_data_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_sender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_weekday',
            field=models.TextField(blank=True, null=True),
        ),
    ]
