# Generated by Django 5.1.1 on 2024-10-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0014_alter_chartdata_chart_data_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='chart_data_wordcloud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='eyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='keyword_max_num',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='total_text_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
