# Generated by Django 5.1.1 on 2024-10-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0015_chartdata_chart_data_wordcloud_chartdata_eyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='eyword',
        ),
    ]
