# Generated by Django 5.1.1 on 2024-10-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0016_remove_chartdata_eyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedata',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
