# Generated by Django 5.1.1 on 2024-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WachatMsgServer', '0018_alter_chartdata_chart_data_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_sender',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_types',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_weekday',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_data_wordcloud',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True),
        ),
    ]
